
import React, { useState, useEffect } from 'react';
import { logger } from '../services/loggerService';

interface GitConfig {
  name: string;
  email: string;
}

const GitConfigForm: React.FC = () => {
  const [config, setConfig] = useState<GitConfig>({ name: '', email: '' });
  const [saved, setSaved] = useState(false);

  useEffect(() => {
    const savedConfig = localStorage.getItem('whisperx_git_config');
    if (savedConfig) {
      setConfig(JSON.parse(savedConfig));
    }
  }, []);

  const handleSave = () => {
    localStorage.setItem('whisperx_git_config', JSON.stringify(config));
    setSaved(true);
    logger.info(`System: Git Identity updated to ${config.name} <${config.email}>`);
    setTimeout(() => setSaved(false), 2000);
  };

  return (
    <div className="prism-card p-6 bg-white space-y-6">
      <div className="flex items-center gap-3 border-b-2 border-black pb-3">
        <div className="w-8 h-8 bg-black text-white flex items-center justify-center prism-shadow">
           <i className="fas fa-id-card text-xs"></i>
        </div>
        <h3 className="text-sm font-black uppercase tracking-widest">Git_Identity_Config</h3>
      </div>
      
      <div className="space-y-4">
        <div className="flex flex-col gap-2">
          <label className="text-[10px] font-black uppercase text-gray-400 tracking-tighter">Global_User_Name</label>
          <input 
            type="text" 
            value={config.name}
            onChange={e => setConfig({...config, name: e.target.value})}
            className="border-4 border-black p-3 mono text-xs font-bold uppercase outline-none focus:bg-yellow-50 focus:prism-shadow transition-all"
            placeholder="ENTER_IDENTITY_HANDLE..."
          />
        </div>
        
        <div className="flex flex-col gap-2">
          <label className="text-[10px] font-black uppercase text-gray-400 tracking-tighter">Transmission_Email</label>
          <input 
            type="email" 
            value={config.email}
            onChange={e => setConfig({...config, email: e.target.value})}
            className="border-4 border-black p-3 mono text-xs font-bold uppercase outline-none focus:bg-yellow-50 focus:prism-shadow transition-all"
            placeholder="RECOVERY_UPLINK@MAIL.DOM"
          />
        </div>

        <button 
          onClick={handleSave}
          className={`w-full py-4 font-black uppercase text-[10px] prism-shadow-active transition-all flex items-center justify-center gap-3 ${saved ? 'bg-green-500 text-black border-green-600' : 'bg-black text-white'}`}
        >
          {saved ? (
            <>
              <i className="fas fa-check-double"></i>
              IDENTITY_STORED_IN_KERNEL
            </>
          ) : (
            <>
              <i className="fas fa-save"></i>
              SAVE_IDENTITY_CONFIG
            </>
          )}
        </button>
      </div>

      <div className="p-3 bg-gray-50 border-2 border-dashed border-gray-300">
        <p className="text-[8px] font-black uppercase text-gray-400 leading-tight">
          These credentials will be associated with all future commits generated by the WhisperX Agent during this session.
        </p>
      </div>
    </div>
  );
};

export default GitConfigForm;
